hrms/announcements/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, DateField, SubmitField
from wtforms.validators import DataRequired, Length


class AnnouncementForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=3, max=100)], render_kw={"class":"form-control"})
    content = TextAreaField('Content', validators=[DataRequired()], render_kw={"class":"form-control", "rows":5})
    ends_at = DateField('End Date', validators=[DataRequired()], render_kw={"class":"form-control"})
    submit = SubmitField('Save Changes', render_kw={"class":"btn btn-primary btn-block"})

hrms/leaves/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField, DateField, SubmitField
from wtforms.validators import DataRequired

class MakeLeaveRequest(FlaskForm):
    leave_type = SelectField('Leave Type', choices=[('Leave of absence', 'Leave of absence'), ('Sick', 'Sick'), ('Maternal', 'Maternal'), ('Study', 'Study'), ('Sabbatical', 'Sabbatical')], validators=[DataRequired()], render_kw={"class":"form-control"})
    from_date = DateField('From Date', validators=[DataRequired()], render_kw={"class":"form-control"})
    to_date = DateField('To Date', validators=[DataRequired()], render_kw={"class":"form-control"})
    submit = SubmitField('Save Changes', render_kw={"class":"btn btn-primary btn-block"})

hrms/announcements/routes.py
from datetime import datetime
from flask import Blueprint, render_template, redirect, request, url_for, flash
from flask_login import current_user, login_required
from hrms import db
from hrms.announcements.forms import AnnouncementForm
from hrms.models import Announcement


announcements = Blueprint('announcements', __name__)


@announcements.route('/admin/announcements')
@login_required
def view_announcements():
    announcements = Announcement.query.order_by(Announcement.ends_at.asc()).all()
    announcements_count = Announcement.query.count()
    return render_template('announcements.html', page_title='Announcements', announcements=announcements, announcements_count=announcements_count, user=current_user)


@announcements.route('/employee/announcements')
@login_required
def employee_view_announcements():
    today = datetime.now().date()
    announcements = Announcement.query.filter(Announcement.ends_at >= today).order_by(Announcement.ends_at.asc()).all()
    announcements_count = len(announcements)
    return render_template('employee/announcements.html', page_title='Announcements', announcements=announcements, announcements_count=announcements_count, user=current_user)


@announcements.route('/admin/announcements/add', methods=['GET', 'POST'])
@login_required
def add_announcement():
    form = AnnouncementForm()
    if form.validate_on_submit():
        announcement = Announcement(title=form.title.data, content = form.content.data, ends_at=form.ends_at.data)
        db.session.add(announcement)
        db.session.commit()
        flash('Announcement was added successfully!', 'success')
        return redirect(url_for('announcements.view_announcements'))

    return render_template('admin/add_announcement.html', page_title='Add Announcement', form=form, user=current_user)


@announcements.route('/admin/announcements/<int:announcement_id>/update', methods=['GET', 'POST'])
@login_required
def update_announcement(announcement_id):
    announcement = Announcement.query.get_or_404(announcement_id)
    form = AnnouncementForm()
    if form.validate_on_submit():
        announcement.title = form.title.data
        announcement.content = form.content.data
        announcement.ends_at = form.ends_at.data
        db.session.commit()
        flash('Announcement has been updated!', 'success')
        return redirect(url_for('announcements.view_announcements', announcement_id=announcement.id))
    elif request.method == 'GET':
        form.title.data = announcement.title
        form.content.data = announcement.content
        form.ends_at.data = announcement.ends_at

    return render_template('admin/add_announcement.html', page_title='Update Announcement', form=form, user=current_user)


@announcements.route('/admin/announcements/<int:announcement_id>/delete', methods=['POST'])
@login_required
def delete_announcement(announcement_id):
    announcement = Announcement.query.get_or_404(announcement_id)

    if request.method == 'POST':
        db.session.delete(announcement)
        db.session.commit()
        flash('Announcement has been deleted!', 'success')
        return redirect(url_for('announcements.view_announcements'))

    return render_template('announcements.html', page_title='Announcements')

hrms/employee/routes.py
from flask import Blueprint, render_template, url_for, redirect, flash
from flask_login import LoginManager, login_user, logout_user, current_user, login_required
from hrms import bcrypt
from hrms.models import User, Announcement, Leave


employee = Blueprint('employee', __name__)


@employee.route('/employee/dashboard')
@login_required
def employee_dashboard():
    announcements_count = Announcement.query.count()
    leaves_count = len(Leave.query.filter_by(employee_id=current_user.id).all())
    return render_template('employee/dashboard.html', page_title='User Dashboard', announcements_count=announcements_count, leaves_count=leaves_count, user=current_user)

hrms/leaves/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import current_user, login_required
from hrms import db
from hrms.leaves.forms import MakeLeaveRequest
from hrms.models import Leave, User


leaves = Blueprint('leaves', __name__)


@leaves.route('/employee/leaves')
@login_required
def employee_view_leaves():
    if current_user.is_authenticated:
        user = current_user.id
        leaves = Leave.query.filter_by(employee_id=user).order_by(Leave.created_at.desc()).all()
        leaves_count = len(leaves)
        return render_template('employee/leaves.html', page_title='Employee Leaves', leaves=leaves, leaves_count=leaves_count, user=current_user)


@leaves.route('/admin/leaves')
@login_required
def admin_view_leaves():
    leaves = db.session.query(Leave, User).join(User).all()
    leaves_count = len(leaves)
    pending_leaves = len([leave for leave, _ in leaves if leave.status == 'pending'])
    return render_template('admin/leaves.html', page_title='Leave Requests', leaves=leaves, leaves_count=leaves_count, pending_leaves=pending_leaves, user=current_user)


@leaves.route('/employee/leaves/request', methods=['GET', 'POST'])
@login_required
def make_leave_request():
    form = MakeLeaveRequest()
    if form.validate_on_submit():
        leave_request = Leave(leave_type=form.leave_type.data, from_date = form.from_date.data, to_date=form.to_date.data, employee_id=current_user.id)
        db.session.add(leave_request)
        db.session.commit()
        flash('Leave Request has been sent!', 'success')
        return redirect(url_for('leaves.employee_view_leaves', user_id=current_user.id))
    return render_template('employee/make_leave_request.html', page_title='Apply for Leave', form=form, user=current_user)


@leaves.route('/admin/leaves/approval/<int:leave_id>/<string:status>', methods=['POST'])
@login_required
def request_approval(leave_id, status):
    leave_request = Leave.query.get_or_404(leave_id)
    leave_request.status = status
    db.session.commit()
    flash(f'Leave request has been {status}!', 'success')
    return redirect(url_for('leaves.admin_view_leaves'))

hrms/templates/employee/announcements.html
{% extends 'main_layout.html' %} {% block body %}
<section class="app">
  {% include "aside.html" %}
  <main>
    <div class="main_container container-fluid pt-2">
      <div class="header p-2 d-flex justify-content-between align-items-center">
        <h6>Announcements ({{ announcements_count }})</h6>
        <input
          type="text"
          id="myInput"
          onkeyup="searchFunction()"
          placeholder="Search Announcements..."
          class="form-control-sm"
        />
      </div>
      {% include 'notification_message.html' %}

      <div class="employee_announcements_wrapper">
        {% for announcement in announcements %}
        <div class="announcement p-3">
          <h5>
            {{ announcement.title }}
            <span
              ><small
                ><i>{{ announcement.ends_at.strftime('%d-%m-%Y') }}</i></small
              ></span
            >
          </h5>
          <p>{{ announcement.content }}</p>
        </div>
        {% endfor %}
      </div>
    </div>
  </main>
</section>

<script src="{{ url_for('static', filename='js/search.js') }}"></script>
{% endblock body %}

hrms/templates/employee/dashboard.html
{% extends 'main_layout.html' %} {% block body %}
<section class="app">
  {% include "aside.html" %}

  <main class="Dashboard">
    <div class="main_container container-fluid dashboard_wrapper p-4">
      <div class="hero container">
        <div class="text">
          <h3>Hello {{ current_user.first_name }}!</h3>
          <p class="text-secondary">Welcome to your dashboard</p>
        </div>
      </div>

      <div class="container stats">
        <div class="stat">
          <h3>{{ leaves_count }}</h3>
          <a
            href="{{ url_for('leaves.employee_view_leaves') }}"
            class="text-dark"
            >Leaves</a
          >
        </div>

        <div class="stat">
          <h3>{{ announcements_count }}</h3>
          <a
            href="{{ url_for('announcements.employee_view_announcements') }}"
            class="text-dark"
            >Announcements</a
          >
        </div>
      </div>
    </div>
  </main>
</section>
{% endblock body %}

hrms/templates/employee/leaves.html
{% extends 'main_layout.html' %} {% block body %}
<section class="app">
  {% include "aside.html" %}
  <main>
    <div class="main_container container-fluid pt-2">
      <div class="header p-2 d-flex justify-content-between align-items-center">
        <h5>Leaves ({{ leaves_count }})</h5>
        <input
          type="text"
          id="myInput"
          onkeyup="searchFunction()"
          placeholder="Search Leaves..."
          class="form-control-sm"
        />
        <a
          href="{{ url_for('leaves.make_leave_request') }}"
          class="btn btn-primary"
          >New Leave Request</a
        >
      </div>
      {% include 'notification_message.html' %}

      <div class="leaves_wrapper">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Leave Type</th>
              <th>From</th>
              <th>To</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {% for leave in leaves %}
            <tr class="searchable">
              <td>{{ leave.leave_type }}</td>
              <td>{{ leave.from_date.strftime('%d-%m-%Y') }}</td>
              <td>{{ leave.to_date.strftime('%d-%m-%Y') }}</td>
              <td
                class="{% if leave.status == 'pending' %}text-primary{% elif leave.status == 'approved'%}text-success{%else%}text-danger{% endif %}"
              >
                {{ leave.status }}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </main>
</section>

<script src="{{ url_for('static', filename='js/search.js') }}"></script>
{% endblock body %}

hrms/templates/employee/make_leave_request.html
{% extends "main_layout.html" %} {% block body %}
<section class="app">
  {% include "aside.html" %}
  <main>
    <div class="main_container container-fluid login">
      <div class="body">
        <form action="" method="post">
          <h1>{{ page_title }}</h1>

          {{ form.hidden_tag() }}

          <div class="row">
            <div class="col">
              <div class="form-group">
                {{ form.leave_type.label }} {% if form.leave_type.errors %} {{
                form.leave_type }} {% for error in form.leave_type.errors %}
                <span class="text-danger">{{ error }}</span>
                {% endfor %} {% else %} {{ form.leave_type }} {% endif %}
              </div>
            </div>

            <div class="col">
              <div class="form-group">
                {{ form.from_date.label }} {% if form.from_date.errors %} {{
                form.from_date }} {% for error in form.from_date.errors %}
                <span class="text-danger">{{ error }}</span>
                {% endfor %} {% else %} {{ form.from_date }} {% endif %}
              </div>
            </div>

            <div class="col">
              <div class="form-group">
                {{ form.to_date.label }} {% if form.to_date.errors %} {{
                form.to_date }} {% for error in form.to_date.errors %}
                <span class="text-danger">{{ error }}</span>
                {% endfor %} {% else %} {{ form.to_date }} {% endif %}
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col">{{ form.submit }}</div>
            <div class="col">
              <a
                href="{{ url_for('leaves.employee_view_leaves') }}"
                class="btn btn-danger btn-block"
                >Cancel</a
              >
            </div>
          </div>
        </form>
      </div>
    </div>
  </main>
</section>
{% endblock body %}