hrms/announcements/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, DateField, SubmitField
from wtforms.validators import DataRequired, Length


class AnnouncementForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=3, max=100)], render_kw={"class":"form-control"})
    content = TextAreaField('Content', validators=[DataRequired()], render_kw={"class":"form-control", "rows":5})
    ends_at = DateField('End Date', validators=[DataRequired()], render_kw={"class":"form-control"})
    submit = SubmitField('Save Changes', render_kw={"class":"btn btn-primary btn-block"})

hrms/announcements/routes.py
from datetime import datetime
from flask import Blueprint, render_template, redirect, request, url_for, flash
from flask_login import current_user, login_required
from hrms import db
from hrms.announcements.forms import AnnouncementForm
from hrms.models import Announcement


announcements = Blueprint('announcements', __name__)


@announcements.route('/admin/announcements')
@login_required
def view_announcements():
    announcements = Announcement.query.order_by(Announcement.ends_at.asc()).all()
    announcements_count = Announcement.query.count()
    return render_template('announcements.html', page_title='Announcements', announcements=announcements, announcements_count=announcements_count, user=current_user)


@announcements.route('/employee/announcements')
@login_required
def employee_view_announcements():
    today = datetime.now().date()
    announcements = Announcement.query.filter(Announcement.ends_at >= today).order_by(Announcement.ends_at.asc()).all()
    announcements_count = len(announcements)
    return render_template('employee/announcements.html', page_title='Announcements', announcements=announcements, announcements_count=announcements_count, user=current_user)


@announcements.route('/admin/announcements/add', methods=['GET', 'POST'])
@login_required
def add_announcement():
    form = AnnouncementForm()
    if form.validate_on_submit():
        announcement = Announcement(title=form.title.data, content = form.content.data, ends_at=form.ends_at.data)
        db.session.add(announcement)
        db.session.commit()
        flash('Announcement was added successfully!', 'success')
        return redirect(url_for('announcements.view_announcements'))

    return render_template('admin/add_announcement.html', page_title='Add Announcement', form=form, user=current_user)


@announcements.route('/admin/announcements/<int:announcement_id>/update', methods=['GET', 'POST'])
@login_required
def update_announcement(announcement_id):
    announcement = Announcement.query.get_or_404(announcement_id)
    form = AnnouncementForm()
    if form.validate_on_submit():
        announcement.title = form.title.data
        announcement.content = form.content.data
        announcement.ends_at = form.ends_at.data
        db.session.commit()
        flash('Announcement has been updated!', 'success')
        return redirect(url_for('announcements.view_announcements', announcement_id=announcement.id))
    elif request.method == 'GET':
        form.title.data = announcement.title
        form.content.data = announcement.content
        form.ends_at.data = announcement.ends_at

    return render_template('admin/add_announcement.html', page_title='Update Announcement', form=form, user=current_user)


@announcements.route('/admin/announcements/<int:announcement_id>/delete', methods=['POST'])
@login_required
def delete_announcement(announcement_id):
    announcement = Announcement.query.get_or_404(announcement_id)

    if request.method == 'POST':
        db.session.delete(announcement)
        db.session.commit()
        flash('Announcement has been deleted!', 'success')
        return redirect(url_for('announcements.view_announcements'))

    return render_template('announcements.html', page_title='Announcements')

hrms/hrm/routes.py
from datetime import datetime
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import current_user, login_required
from hrms import db, bcrypt
from hrms.hrm.forms import CreateUserForm, UpdateEmployeeForm
from hrms.models import User, Department, Occupation, Announcement, Leave


admin = Blueprint('admin', __name__)


@admin.route('/admin/dashboard')
@login_required
def admin_dashboard():
    employees_count = User.query.filter(User.user_level == 1).count()
    departments_count = Department.query.count()
    occupations_count = Occupation.query.count()

    today = datetime.now().date()
    announcements = Announcement.query.filter(Announcement.ends_at >= today).order_by(Announcement.ends_at.asc()).all()
    announcements_count = Announcement.query.count()

    latest_pending_leaves = db.session.query(Leave, User).join(User).filter(Leave.status == 'pending').order_by(Leave.created_at.desc()).limit(4).all()
    leaves_count = Leave.query.count()
    return render_template('admin/dashboard.html', page_title='Admin Dashboard', employees_count=employees_count, departments_count=departments_count, occupations_count=occupations_count, announcements=announcements, announcements_count=announcements_count,latest_pending_leaves=latest_pending_leaves, leaves_count=leaves_count, user=current_user)


@admin.route('/admin/employees')
@login_required
def employees():
    employees = db.session.query(User, Occupation).join(Occupation).filter(User.user_level == 1).order_by(User.first_name.asc()).all()
    employees_count = len(employees)
    return render_template('admin/employees.html', page_title='Employees', employees=employees, employees_count=employees_count, user=current_user)


@admin.route('/admin/add_employee', methods=['GET', 'POST'])
@login_required
def add_employee():
    form = CreateUserForm()
    if form.validate_on_submit():
        temporary_password = "employee"
        hashed_password = bcrypt.generate_password_hash(
            temporary_password).decode('utf-8')
        employee = User(first_name=form.first_name.data, last_name=form.last_name.data, gender=form.gender.data, dob=form.dob.data, email_address=form.email_address.data,
                        phone_number=form.phone_number.data, national_id=form.national_id.data, occupation_id=form.occupation.data, password=hashed_password)
        db.session.add(employee)
        db.session.commit()
        flash('Employee has been added!', 'success')
        return redirect(url_for('admin.employees'))

    return render_template('admin/add_employee.html', page_title='Add Employee', form=form, user=current_user)


@admin.route('/admin/employees/<int:employee_id>/update', methods=['GET', 'POST'])
@login_required
def update_employee(employee_id):
    employee = User.query.get_or_404(employee_id)
    form = UpdateEmployeeForm()
    if form.validate_on_submit():
        employee.first_name = form.first_name.data
        employee.last_name = form.last_name.data
        employee.gender = form.gender.data
        employee.dob = form.dob.data
        employee.email_address = form.email_address.data
        employee.phone_number = form.phone_number.data
        employee.national_id = form.national_id.data
        employee.occupation_id = form.occupation.data
        employee.user_level = form.user_level.data
        db.session.commit()
        flash('Employee has been updated!', 'success')
        return redirect(url_for('admin.employees', employee_id=employee.id))
    elif request.method == 'GET':
        form.first_name.data = employee.first_name
        form.last_name.data = employee.last_name
        form.gender.data = employee.gender
        form.dob.data = employee.dob
        form.email_address.data = employee.email_address
        form.phone_number.data = employee.phone_number
        form.national_id.data = employee.national_id
        form.occupation.data = str(employee.occupation_id)  # Convert to str for SelectField
        form.user_level.data = str(employee.user_level)  # Convert to str for SelectField

    return render_template('admin/add_employee.html', page_title='Update Employee', form=form, user=current_user)


@admin.route('/admin/employees/<int:employee_id>/delete', methods=['POST'])
@login_required
def delete_employee(employee_id):
    employee = User.query.get_or_404(employee_id)

    if request.method == 'POST':
        db.session.delete(employee)
        db.session.commit()
        flash('Employee has been deleted!', 'success')
        return redirect(url_for('admin.employees'))

    return render_template('admin/employees.html', page_title='Employees')

hrms/main/routes.py
from flask import Blueprint, render_template
from flask_login import current_user


main = Blueprint('main', __name__)


@main.route('/')
def home():
    return render_template('main/index.html')


@main.route('/about')
def about():
    return render_template('main/about.html')

hrms/users/routes.py
import os
from datetime import datetime
from flask import Blueprint, render_template, redirect, url_for, flash, current_app, request
from flask_login import LoginManager, login_user, logout_user, current_user
from hrms import db, bcrypt
from .forms import LoginForm, UpdateProfilePictureForm, UpdatePasswordForm
from .utils import save_picture
from hrms.models import User


user = Blueprint('user', __name__)
login_manager = LoginManager()


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


@user.route('/login', methods=['GET', 'POST'])
@user.route('/user/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(
            email_address=form.email_address.data).first()

        if user and bcrypt.check_password_hash(user.password, form.password.data):
            # check if the user is an admin
            if user.user_level == 2:
                login_user(user)
                return redirect(url_for('admin.admin_dashboard'))
            else:
                login_user(user)
                return redirect(url_for('employee.employee_dashboard'))
        else:
            flash('Oops! Check your credentials!', 'danger')

    return render_template('login.html', page_title='Login', form=form)


def get_profile_picture(employee_id):
    user = User.query.get_or_404(employee_id)
    profile_picture = url_for('static', filename='images/profile_pictures/' + user.image_file)
    return profile_picture


@user.route('/user/profile_settings/<int:employee_id>')
def profile_settings(employee_id):
    profile_picture = get_profile_picture(employee_id=employee_id)
    return render_template('profile_settings.html', page_title='Profile Settings', profile_picture=profile_picture, user=current_user)


@user.route('/user/update_password/<int:employee_id>', methods=['GET', 'POST'])
def update_password(employee_id):
    employee = User.query.get_or_404(employee_id)
    profile_picture = get_profile_picture(employee_id=employee_id)
    password_form = UpdatePasswordForm()
    if password_form.validate_on_submit():
        password = password_form.new_password.data
        hashed_password = bcrypt.generate_password_hash(
            password).decode('utf-8')
        employee.password = hashed_password
        db.session.commit()
        flash('Password has been updated!', 'success')
        return redirect(url_for('user.login'))

    return render_template('update_password.html', page_title='Update Password', profile_picture=profile_picture, password_form=password_form, user=current_user)


@user.route('/user/update_profile/<int:employee_id>', methods=['GET', 'POST'])
def update_profile(employee_id):
    employee = User.query.get_or_404(employee_id)
    profile_picture = get_profile_picture(employee_id=employee_id)
    form = UpdateProfilePictureForm()
    if form.validate_on_submit():
        if form.profile_picture.data:
            if employee.image_file and employee.image_file != 'default.jpg':
                try:
                    old_profile_picture = os.path.join(current_app.root_path, 'static/images/profile_pictures', employee.image_file)
                    os.remove(old_profile_picture)
                except Exception as e:
                    print(f"Error deleting the old image: {e}")

            picture_file = save_picture(form.profile_picture.data)
            employee.image_file = picture_file
        db.session.commit()
        flash('Profile Image has been updated!', 'success')
        return redirect(url_for('user.update_profile', employee_id=employee_id))

    return render_template('update_profile.html', page_title='Update Profile', form=form, profile_picture=profile_picture, user=employee)


@user.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('user.login'))

hrms/templates/announcements.html
{% extends 'main_layout.html' %} {% block body %}
<section class="app">
  {% include 'admin/aside.html' %}
  <main>
    <div class="main_container container-fluid pt-2">
      <div class="header p-2 d-flex justify-content-between align-items-center">
        <h5>Announcements ({{ announcements_count }})</h5>
        <input
          type="text"
          id="myInput"
          onkeyup="searchFunction()"
          placeholder="Search Announcements..."
          class="form-control-sm"
        />
        <a
          href="{{ url_for('announcements.add_announcement') }}"
          class="btn btn-primary"
          >New Announcement</a
        >
      </div>
      {% include 'notification_message.html' %}

      <div class="announcements_wrapper">
        {% for announcement in announcements %}
        <div class="announcement list-group list-group-flush searchable">
          <li
            class="list-group-item d-flex justify-content-between align-items-center"
          >
            <span>
              <a
                href="{{ url_for('announcements.update_announcement', announcement_id=announcement.id) }}"
              >
                {{ announcement.title }} - {{ announcement.content }}
                <i class="text-secondary">{{ announcement.ends_at }}</i>
              </a>
            </span>

            <form
              action="{{ url_for('announcements.delete_announcement', announcement_id=announcement.id) }}"
              method="post"
              onsubmit="return confirm('Are you sure you want to delete this announcement?');"
            >
              <button type="submit" class="btn text-danger">
                <span class="icon icon-trash"></span>
              </button>
            </form>
          </li>
        </div>
        {% endfor %}
      </div>
    </div>
  </main>
</section>

<script src="{{ url_for('static', filename='js/search.js') }}"></script>
{% endblock body %}

hrms/templates/aside.html
<aside>
  <h1 class="mt-3">HRClarity</h1>

  <div class="container text-center mt-4">
    <img src="{{ url_for('static', filename='images/profile_pictures/' ~ current_user.image_file ) }}" alt="Employee" class="rounded-circle" width="90" height="90" />
  </div>

  <div class="links">
    <ul>
        {% if current_user.user_level > 1 %}
            <li>
                <a href="{{ url_for('admin.admin_dashboard') }}">
                    <span class="icon icon-home"></span>
                    <span>Dashboard</span>
                </a>
            </li>

            <li>
                <a href="{{ url_for('admin.employees') }}">
                    <span class="icon icon-users"></span>
                    <span>Employees</span>
                </a>
            </li>

            <li>
                <a href="{{ url_for('leaves.admin_view_leaves') }}">
                    <span class="icon icon-car"></span>
                    <span>Leaves</span>
                </a>
            </li>

            <li>
                <a href="{{ url_for('announcements.view_announcements') }}">
                    <span class="icon icon-speaker"></span>
                    <span>Announcements</span>
                </a>
            </li>

            <li class="nav-item dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false"><span class="icon icon-building"></span>Organization</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item text-dark" href="{{ url_for('organization.departments') }}">
                    <span class="icon icon-work"></span>
                    <span>Departments</span>
                </a>
                <a class="dropdown-item text-dark" href="{{ url_for('organization.occupations') }}">
                    <span class="icon icon-briefcase"></span>
                    <span>Occupations</span></a>
                </div>
            </li>
      {% endif %}

      {% if current_user.user_level == 1 %}
        <li>
            <a href="{{ url_for('employee.employee_dashboard') }}">
                <span class="icon icon-home"></span>
                <span>Dashboard</span>
            </a>
        </li>

        <li>
            <a href="{{ url_for('leaves.employee_view_leaves') }}">
                <span class="icon icon-car"></span>
                <span>Leaves</span>
            </a>
        </li>

        <li>
            <a href="{{ url_for('announcements.employee_view_announcements') }}">
                <span class="icon icon-speaker"></span>
                <span>Announcements</span>
            </a>
        </li>
      {% endif %}
    </ul>


    <ul>
      <li>
        <a href="{{ url_for('user.profile_settings', employee_id=current_user.id) }}">
            <span class="icon icon-user"></span>
            <span>{{ user.first_name }} {{ user.last_name }}</span>
        </a>
      </li>
      <li>
        <a href="{{ url_for('user.logout') }}">
            <span class="icon icon-power-off"></span>
            <span>Logout</span>
        </a>
      </li>
    </ul>
  </div>
</aside>

hrms/templates/index.html
{% extends "main_layout.html" %} {% block body %} {% include 'navbar.html' %}
<section class="Homepage">
  <div class="hero_section">
    <h1>HRClarity</h1>
    <p>Human Resource Management made easy</p>
  </div>

  <section class="About" id="About">
    <div class="container">
      <p>
        HRClarity is all about bringing clarity to your human resources
        management. We understand that your most valuable assets are your
        people, and we're here to help you nurture, manage, and empower them
        like never before.
      </p>
      <p>HRClarity promises:</p>
      <ul>
        <li>
          Simplicity: We believe that HR management should be simple. Our
          user-friendly tools make it easy to navigate complex HR processes.
        </li>
        <li>
          Insights: Unlock the potential of your data with powerful analytics.
          Make informed decisions that drive your business forward.
        </li>
        <li>
          Support: Our dedicated team is here for you. We're not just a service;
          we're your HR partner.
        </li>
      </ul>
    </div>
  </section>

  <section class="Features" id="Features">
    <div class="features_wrapper container">
      <div class="feature">
        <div class="details">
          <h1>Employees</h1>
          <p>
            Verifying, viewing and updating employees data has never been
            easier. Experience the power of easily searching through all the
            employees in the organization.
          </p>
        </div>
        <div class="image">
          <img
            src="{{ url_for('static', filename='images/employees.png') }}"
            alt="Employees"
          />
        </div>
      </div>

      <div class="feature">
        <div class="details">
          <h1>Leaves</h1>
          <p>
            Making leave requests has never been easier. With just a few details
            to fill in, your request is sent and ready to be reviewed by the HR.
          </p>
        </div>
        <div class="image">
          <img
            src="{{ url_for('static', filename='images/leaves.png') }}"
            alt="Leaves"
          />
        </div>
      </div>

      <div class="feature">
        <div class="details">
          <h1>Announcements</h1>
          <p>
            HR managers can easily make announcements viewable by all employees
            in the organization.
          </p>
        </div>
        <div class="image">
          <img
            src="{{ url_for('static', filename='images/announcements.png') }}"
            alt="Announcements"
          />
        </div>
      </div>
    </div>
  </section>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col">
          <h4>HRClarity</h4>
        </div>

        <div class="col">
            <h4>Products</h4>
            <p>Time and Attendance</p>
            <p>Payroll, compliance & payrolls</p>
            <p>Perks and Benefits</p>
            <p>Perfomance Management</p>
            <p>Expense claims</p>
            <p>Leaves and Time off</p>
            <p>EOR Services</p>
        </div>

        <div class="col">
          <h4>Built for You</h4>
          <p>Startups</p>
          <p>Banks</p>
          <p>Hospitality</p>
          <p>Retail</p>
          <p>Construction</p>
          <p>Healthcare</p>
          <p>Manufacturing</p>
        </div>

        <div class="col">
            <h4>Resources</h4>
            <p>About us</p>
            <p>Careers</p>
            <p>Pricing</p>
            <p>Partners</p>
            <p>Blog</p>
            <p>Knowledgebase</p>
            <p>Customer Testimonials</p>
        </div>

        <div class="col">
            <h4>Socials</h4>
            <p>
                Contribute on Github: <span class="icon icon-github"></span>
                <a href="https://github.com/AlexAaqil/HRClarity"></a>
          </p>
        </div>
      </div>
    </div>

    <div class="copyright mt-4 border-top p-2">
      <p>&copy; 2023 | All rights reserved | Made by AlexAaqil</p>
    </div>
  </footer>
</section>
{% endblock body %}

hrms/templates/login.html
{% extends "main_layout.html" %}

{% block body %}
{% include 'main/navbar.html' %}
<section class="Authentication">
    <div class="container login">
        <div class="body">
            {% include 'notification_message.html' %}
            <form action="" method="post">
                <h1>{{ page_title }}</h1>

                {{ form.hidden_tag() }}

                <div class="form-group">
                    {{ form.email_address.label }}
                    {% if form.email_address.errors %}
                        {{ form.email_address(class="form-control invalid_input") }}
                        {% for error in form.email_address.errors %}
                            <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    {% else %}
                        {{ form.email_address }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.password.label }}
                    {{ form.password }}
                </div>

                <div class="form-group">
                    {{ form.submit }}
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock body %}

hrms/templates/main_layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='/css/icomoon.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='/css/bootstrap.min.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='/css/styles.css') }}"
    />
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <title>HRClarity {% if page_title %} | {{ page_title }} {% endif %}</title>
  </head>
  <body>
    {% block body %} {% endblock body %}
  </body>
</html>

hrms/templates/navbar.html
<nav class="home_navbar">
  <div class="container">
    <a href="{{ url_for('main.home') }}" class="brand">HRClarity</a>
    <ul>
      <li><a href="{{ url_for('main.home') }}">Home</a></li>
      <li>
        <a href="{{ url_for('user.login') }}" class="action_btn">Login</a>
      </li>
    </ul>
  </div>
</nav>

hrms/templates/notification_message.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismissible fade show">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

hrms/templates/profile_settings.html
{% extends "main_layout.html" %} {% block body %}
<section class="app">
  {% include "aside.html" %}
  <main>
    <div class="main_container container-fluid login">
      <div class="body">

        <h3 class="text-center p-3">Settings</h3>

        <div class="container row justify-content-center mt-4">
            <div class="d-flex position-relative d-flex justify-content-center col col-lg-4 p-0">
                <a href="{{ url_for('user.update_profile', employee_id=current_user.id) }}" class="stretched-link text-dark">
                    <h5 class="bg-info text-white text-center p-4"><span class="icon icon-user"></span> Profile</h5>
                </a>
            </div>

            <div class="d-flex position-relative d-flex justify-content-center col col-lg-4 p-0">
                <a href="{{ url_for('user.update_password', employee_id=current_user.id) }}" class="stretched-link text-dark">
                    <h5 class="bg-info text-white text-center p-4"><span class="icon icon-lock"></span> Password</h5>
                </a>
            </div>
        </div>

      </div>
    </div>
  </main>
</section>
{% endblock body %}

hrms/templates/update_password.html
{% extends "main_layout.html" %}
{% block body %}
<section class="app">
  {% include "aside.html" %}
  <main>
    <div class="main_container container-fluid login">
      <div class="body">
        <nav aria-label="breadcrumb" class="row justify-content-center mt-3 mb-3">
            <ol class="breadcrumb col col-lg-11 d-flex justify-content-center">
                <li class="breadcrumb-item"><a href="{{ url_for('user.profile_settings', employee_id=current_user.id) }}">Profile Settings</a></li>
                <li class="breadcrumb-item active" aria-current="page">Update Password</li>
            </ol>
        </nav>

        <div class="row">
            <div class="col col-lg-2 text-center">
                <img class="rounded-circle" src="{{ profile_picture }}" alt="User's Picture" width="110" height="110">
            </div>

            <div class="col col-lg-10 d-flex flex-column justify-content-center">
                <h5>{{ current_user.first_name }} {{ current_user.last_name }}</h5>
                <p>{{ current_user.email_address }}</p>
            </div>
        </div>

        {% include 'notification_message.html' %}

        <form action="" method="post">
          <h1>{{ page_title }}</h1>

          {{ password_form.hidden_tag() }}

          <div class="row">
            <div class="col">
              <div class="form-group">
                {{ password_form.new_password.label }}
                {% if password_form.new_password.errors %}
                    {{ password_form.new_password }}
                        {% for error in password_form.new_password.errors %}
                            <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                {% else %}
                    {{ password_form.new_password }}
                {% endif %}
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col">{{ password_form.submit }}</div>
          </div>
        </form>

      </div>
    </div>
  </main>
</section>
{% endblock body %}

hrms/templates/update_profile.html
{% extends "main_layout.html" %} {% block body %}
<section class="app">
  {% include "aside.html" %}
  <main>
    <div class="main_container container-fluid login">
      <div class="body">
        <nav aria-label="breadcrumb" class="row justify-content-center mt-3 mb-3">
            <ol class="breadcrumb col col-lg-11 d-flex justify-content-center">
                <li class="breadcrumb-item"><a href="{{ url_for('user.profile_settings', employee_id=current_user.id) }}">Profile Settings</a></li>
                <li class="breadcrumb-item active" aria-current="page">Update Profile</li>
            </ol>
        </nav>

        <div class="row">
            <div class="col col-lg-2 text-center">
                <img class="rounded-circle" src="{{ profile_picture }}" alt="User's Picture" width="110" height="110">
            </div>

            <div class="col col-lg-10 d-flex flex-column justify-content-center">
                <h5>{{ current_user.first_name }} {{ current_user.last_name }}</h5>
                <p>{{ current_user.email_address }}</p>
            </div>
        </div>

        {% include 'notification_message.html' %}

        <form action="" method="post" enctype="multipart/form-data">
            <h1>Update Profile Picture</h1>

            {{ form.hidden_tag() }}

            <div class="form-group">
                {{ form.profile_picture.label }}
                {{ form.profile_picture }}
                {% if form.profile_picture.errors %}
                    {% for error in form.profile_picture.errors %}
                        {{ error }}
                    {% endfor %}
                {% endif %}
            </div>

            <div class="row">
                <div class="col">{{ form.submit }}</div>
            </div>
        </form>

      </div>
    </div>
  </main>
</section>
{% endblock body %}