hrms/main/routes.py
from flask import Blueprint, render_template
from flask_login import current_user


main = Blueprint('main', __name__)


@main.route('/')
def home():
    return render_template('main/index.html')


@main.route('/about')
def about():
    return render_template('main/about.html')

hrms/templates/main/about.html
{% extends "main_layout.html" %} {% block body %} {% include 'main/navbar.html' %}
<section class="About">
  <div class="jumbotron bg-primary text-white mb-5 hero">
    <div class="container">
        <h2 class="text-center">Our mission is to enhance the efficiency Human Resource Managers when managing the greatest asset of their organization, the employees.</h2>
    </div>
  </div>

  <div class="container mt-5 mb-5 core_values">
    <h3 class="text-center mb-5">Our Core Values</h3>
    <div class="container row">
        <div class="col col-lg-6 d-flex align-items-center">
            <div class="icon text-center">
                <span class="icon icon-event_busy"></span>
            </div>
            <div class="text">
                <h4>Resourcefulness</h4>
                <p>Employees are the greatest asset and managing them effectively is the most challenging part. Not to worry though because we help you through every step of the way.</p>
            </div>
        </div>

        <div class="col col-lg-6 d-flex align-items-center">
            <div class="icon text-center">
                <span class="icon icon-chain"></span>
            </div>
            <div class="text">
                <h4>Integrity</h4>
                <p>Our word is our bond. We do what we promise by making the right choices and not the easy or popular choices.</p>
            </div>
        </div>

        <div class="col col-lg-6 d-flex align-items-center">
            <div class="icon text-center">
                <span class="icon icon-lightbulb-o"></span>
            </div>
            <div class="text">
                <h4>Curiosity</h4>
                <p>We are well-experienced but we don’t know everything. That’s why we keep an open mind and are always ready to try out new things..</p>
            </div>
        </div>

        <div class="col col-lg-6 d-flex align-items-center">
            <div class="icon text-center">
                <span class="icon icon-lightbulb-o"></span>
            </div>
            <div class="text">
                <h4>Curiosity</h4>
                <p>Our word is our bond. We do what we promise by making the right choices and not the easy or popular choices.</p>
            </div>
        </div>
    </div>
  </div>

  <div class="container mt-5 mb-5 the_team">
    <h3 class="text-center">Meet the Team</h3>
    <p class="text-center mb-5">Team work is dream work</p>
    <div class="row justify-content-center">
        <div class="col text-center">
            <img src="{{ url_for('static', filename='images/default.jpg') }}" alt="Profile_Pic" class="rounded-circle" width="100" height="100">
        </div>

        <div class="col text-center">
            <img src="{{ url_for('static', filename='images/default.jpg') }}" alt="Profile_Pic" class="rounded-circle" width="100" height="100">
        </div>

        <div class="col text-center">
            <img src="{{ url_for('static', filename='images/default.jpg') }}" alt="Profile_Pic" class="rounded-circle" width="100" height="100">
        </div>

        <div class="col text-center">
            <img src="{{ url_for('static', filename='images/default.jpg') }}" alt="Profile_Pic" class="rounded-circle" width="100" height="100">
        </div>

        <div class="col text-center">
            <img src="{{ url_for('static', filename='images/default.jpg') }}" alt="Profile_Pic" class="rounded-circle" width="100" height="100">
        </div>
    </div>
  </div>

  <div class="container mt-5 mb-5 partners">
    <h3 class="text-center">Our Partners & Investors</h3>
    <p class="text-center mb-5">We are trusted by many.</p>
    <div class="row justify-content-center">
        <div class="col text-center">
            <h5>Naomi's Village</h5>
        </div>

        <div class="col text-center">
            <h5>Aaqil Softwares</h5>
        </div>
    </div>
  </div>

  <div class="container mt-5 mb-5 location">
    <h3 class="text-center">Find Us</h3>
    <p class="text-center">Our office is located at the 15th floor, Garden City Business Park,</p>
    <p class="text-center">Garden City, Nairobi.</p>
  </div>

  {% include 'main/footer.html' %}
</section>
{% endblock body %}

hrms/templates/main/footer.html
  <footer class="pt-5 pb-5">
    <div class="container">
      <div class="row">
        <div class="col">
          <h4>HRClarity</h4>
        </div>

        <div class="col">
            <h4>Products</h4>
            <p>Time and Attendance</p>
            <p>Payroll, compliance & payrolls</p>
            <p>Perks and Benefits</p>
            <p>Perfomance Management</p>
            <p>Expense claims</p>
            <p>Leaves and Time off</p>
            <p>EOR Services</p>
        </div>

        <div class="col">
          <h4>Built for You</h4>
          <p>Startups</p>
          <p>Banks</p>
          <p>Hospitality</p>
          <p>Retail</p>
          <p>Construction</p>
          <p>Healthcare</p>
          <p>Manufacturing</p>
        </div>

        <div class="col">
            <h4>Resources</h4>
            <p><a href="{{ url_for('main.about') }}">About us</a></p>
            <p>Careers</p>
            <p>Pricing</p>
            <p>Partners</p>
            <p>Blog</p>
            <p>Knowledgebase</p>
            <p>Customer Testimonials</p>
        </div>

        <div class="col">
            <h4>Socials</h4>
            <p>
                Contribute on Github: <span class="icon icon-github"></span>
                <a href="https://github.com/AlexAaqil/HRClarity"></a>
          </p>
        </div>
      </div>
    </div>

    <div class="copyright mt-4 border-top pt-2">
      <p>&copy; 2023 | All rights reserved | Made by AlexAaqil</p>
    </div>
  </footer>

hrms/templates/main/index.html
{% extends "main_layout.html" %} {% block body %} {% include 'main/navbar.html' %}
<section class="Homepage">
  <div class="hero_section">
    <h1>HRClarity</h1>
    <p>Human Resource Management made easy</p>
  </div>

  <section class="mt-5 mb-5 About" id="About">
    <div class="container">
      <p>
        HRClarity is all about bringing clarity to your human resources
        management. We understand that your most valuable assets are your
        people, and we're here to help you nurture, manage, and empower them
        like never before.
      </p>
      <p>HRClarity promises:</p>
      <ul>
        <li>
          Simplicity: We believe that HR management should be simple. Our
          user-friendly tools make it easy to navigate complex HR processes.
        </li>
        <li>
          Insights: Unlock the potential of your data with powerful analytics.
          Make informed decisions that drive your business forward.
        </li>
        <li>
          Support: Our dedicated team is here for you. We're not just a service;
          we're your HR partner.
        </li>
      </ul>
    </div>
  </section>

  <section class="Features" id="Features">
    <div class="features_wrapper container">
      <div class="feature">
        <div class="details">
          <h1>Employees</h1>
          <p>
            Verifying, viewing and updating employees data has never been
            easier. Experience the power of easily searching through all the
            employees in the organization.
          </p>
        </div>
        <div class="image">
          <img
            src="{{ url_for('static', filename='images/employees.png') }}"
            alt="Employees"
          />
        </div>
      </div>

      <div class="feature">
        <div class="details">
          <h1>Leaves</h1>
          <p>
            Making leave requests has never been easier. With just a few details
            to fill in, your request is sent and ready to be reviewed by the HR.
          </p>
        </div>
        <div class="image">
          <img
            src="{{ url_for('static', filename='images/leaves.png') }}"
            alt="Leaves"
          />
        </div>
      </div>

      <div class="feature">
        <div class="details">
          <h1>Announcements</h1>
          <p>
            HR managers can easily make announcements viewable by all employees
            in the organization.
          </p>
        </div>
        <div class="image">
          <img
            src="{{ url_for('static', filename='images/announcements.png') }}"
            alt="Announcements"
          />
        </div>
      </div>
    </div>
  </section>

  {% include 'main/footer.html' %}
</section>
{% endblock body %}

hrms/templates/main/navbar.html
<nav class="home_navbar">
  <div class="container">
    <a href="{{ url_for('main.home') }}" class="brand">HRClarity</a>
    <ul>
      <li><a href="#">Features</a></li>
      <li><a href="{{ url_for('main.about') }}">About us</a></li>
    </ul>

    <ul>
      <li>
        <a href="{{ url_for('user.login') }}" class="action_btn">Login</a>
      </li>
    </ul>
  </div>
</nav>